### ISSUE TITLE
Is there any way to make this work with postcss-mixins?

### ISSUE THREAD

**Issue by sandrina-p** [GitScrum/postcss-at-rules-variables#140]
I have a mixin made with [postcss-mixins](https://github.com/postcss/postcss-mixins) and I want to use a css variable as argument, but it isn't working.

    :root {
        --padd: 2rem;
    }

    @define-mixin position $place, $val {
        @if $place == end { right: $(val); }
        @if $place == start { left: $(val); }
    }

And then I call it:

    .foo1 {
       @mixin position end, 2rem; /* it works -> right: 2rem; */
    }
    
    .foo2 {
       @mixin position end, var(--padd); /* doesn't work -> right: var(--padd); - it should output 2rem  */
    }

Is is possible for you to make this works with `postcss-at-rules-variables`?

**Comment by GitScrum** [comment]
@sandrina-p Hi, of course, you need use options `atRules`
```js
require('postcss-at-rules-variables')({ atRules: ['mixin'] })
```

**Comment by sandrina-p** [comment]
Thanks, it worked!
