### ISSUE TITLE
Any Chance of @import?

### ISSUE THREAD

**Issue by trisys3** [GitScrum/postcss-at-rules-variables#178]
Would you be able to support `@import`?

We use variables in `@import` rules, mainly for theming. We currently use a lot of LESS because of Bootstrap, but we are trying to switch to PostCSS. Right now, we have only 1 filename with variables, but we have to concatenate it separately. `@import`ing it directly from another CSS file would be nice. Also, if we have more files with variables in the name, this could obviously become an issue.

**Comment by GitScrum** [comment]
@trisys3 Hi, I apologize for the long answer, I rested)
Сould you give an example of how this should work?

**Comment by trisys3** [comment]
Nevermind, it looks like you already have an example of this in the README. I guess that'll teach me to read and *understand* everything before I comment.
